Repository DJ2LS/FreeDATA, pull requests merged in 2022-06, with the labels that each got.

#206 update info fields
  gui/main.js
  gui/package.json
  gui/preload-chat.js
  gui/preload-main.js
  gui/sock.js
  gui/src/chat-module.html
  gui/src/index.html
  tnc/data_handler.py
  tnc/sock.py
  tnc/static.py
Labels: TNC, GUI

#208 Fix for issue #207.
  tnc/data_handler.py
Labels: bug, ARQ

#216 Add FRAME_TYPE enum to static
  tnc/static.py
Labels: enhancement

#215 Make log_handler a little more flexible.
  tnc/log_handler.py
Labels: enhancement

#214 Tests 2022-Jun
  .github/workflows/ctest.yml
  CMakeLists.txt
  README.md
  test/001_highsnr_stdio_audio/test_virtual3.sh
  test/README.md
  test/test_arq_short.py
  test/test_chat_text.py
  test/test_datac0.py
  test/test_helpers.py
  test/test_highsnr_stdio_C_P_datacx.py
  test/test_highsnr_stdio_P_C_datacx.py
  test/test_highsnr_stdio_P_P_datacx.py
  test/test_highsnr_stdio_P_P_multi.py
  test/test_modem.py
  test/test_tnc.py
  test/test_tnc_IRS.py
  test/test_tnc_states.py
  test/test_virtual1.sh
  test/test_virtual1a.sh
  test/test_virtual1b.sh
  test/test_virtual1c.sh
  test/test_virtual2.sh
  test/test_virtual3a.sh
  test/test_virtual3b.sh
  test/test_virtual4a.sh
  test/test_virtual4b.sh
  test/test_virtual_mm.sh
  test/util_callback_multimode_rx.py
  test/util_callback_multimode_rx_outside.py
  test/util_callback_multimode_tx.py
  test/util_callback_rx.py
  test/util_callback_rx_outside.py
  test/util_callback_tx.py
  test/util_chat_text_1.py
  test/util_chat_text_2.py
  test/util_datac0.py
  test/util_multimode_rx.py
  test/util_multimode_tx.py
  test/util_rx.py
  test/util_tnc_IRS.py
  test/util_tnc_ISS.py
  test/util_tx.py
  tnc/audio.py
  tnc/codec2.py
  tnc/data_handler.py
  tnc/helpers.py
  tnc/main.py
  tnc/sock.py
Labels: enhancement

#219 Issue 218 fix with test
  test/test_chat_text.py
  test/util_chat_text_1.py
  test/util_chat_text_2.py
  tnc/data_handler.py
Labels: bug, ARQ, TNC

#221 Use FRAME_TYPE enum instead of plain int.
  tnc/data_handler.py
  tnc/static.py
Labels: enhancement
