Repository DJ2LS/FreeDATA, pull requests merged in 2025-02, with the labels that each got.

#881 fixing missing map information on wrong locator
  freedata_gui/src/components/grid/grid_stations_map.vue
Labels: GUI

#879 macOS install Scripts v0.0.1
  tools/macOS/README.md
  tools/macOS/install-freedata-macos.sh
  tools/macOS/run-freedata-macos.sh
Labels: feature request

#889 Move API Endpoints to subfolders
  freedata_server/api/__init__.py
  freedata_server/api/command_helpers.py
  freedata_server/api/common.py
  freedata_server/api/config.py
  freedata_server/api/devices.py
  freedata_server/api/freedata.py
  freedata_server/api/general.py
  freedata_server/api/modem.py
  freedata_server/api/radio.py
  freedata_server/api/websocket.py
  freedata_server/server.py
  tests/test_message_protocol.py
Labels: enhancement
